/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the locked 7-layer pipeline on a source document */
        post: operations["analyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description Human-readable error message */
            detail: string;
        };
        /** @enum {string} */
        ContentType: "xml" | "html" | "json" | "text";
        AnalyzeOptions: {
            /**
             * @description Defaults to false. Requires valid x-analyze-secret header to execute.
             * @default false
             */
            run_meaning: boolean;
            /** @default true */
            run_origin: boolean;
            /** @default true */
            run_verification: boolean;
        };
        AnalyzeRequest: {
            /** @description Raw document text */
            content: string;
            content_type: components["schemas"]["ContentType"];
            options?: components["schemas"]["AnalyzeOptions"];
        };
        InputResult: {
            /** @description Preserved raw input exactly as received */
            raw_content: string;
            /** @description Content type as provided in request */
            content_type: string;
            /** @description Size in bytes (UTF-8 encoded) */
            size: number;
            /**
             * @description Well-formedness validation result
             * @enum {string}
             */
            parse_status: "ok" | "error";
            /**
             * @description Parse error messages if parse_status is error
             * @default []
             */
            parse_errors: string[];
        };
        StructureNode: {
            /** @description Unique node identifier, path-addressable back to source */
            node_id: string;
            /** @description Position reference in source document (e.g. char:0-42, xpath:section[0], jsonpath:$.body) */
            source_anchor: string;
            /** @description Original text span, unmodified */
            source_text: string;
            /** @description LNS-normalized text (whitespace/line cleanup only, no semantic rewriting) */
            normalized_text: string;
            /** @description AAC: explicit actor if present */
            actor?: string | null;
            /** @description AAC: explicit action if present */
            action?: string | null;
            /** @description AAC: explicit condition if present */
            condition?: string | null;
            /** @description TPS: explicit deadline, trigger, timing if present */
            temporal?: string | null;
            /** @description SJM: explicit system, jurisdiction, authority if present */
            jurisdiction?: string | null;
            /** @description MPS: explicit enforcement, process step, procedural flow if present */
            mechanism?: string | null;
            /** @description RDS: separated likelihood and impact language */
            risk?: {
                likelihood?: string | null;
                impact?: string | null;
            } | null;
            /** @description Extraction signal tags (e.g. has_actor, has_temporal) */
            tags: string[];
            /** @description CFS violation flags (intent_attribution, emotional_labeling, causal_inference, narrative_language) */
            blocked_flags: string[];
            /** @description 5W1H: explicit who if directly present */
            who?: string | null;
            /** @description 5W1H: explicit what if directly present */
            what?: string | null;
            /** @description 5W1H: explicit when if directly present */
            when?: string | null;
            /** @description 5W1H: explicit where if directly present */
            where?: string | null;
            /** @description 5W1H: explicit why if directly present */
            why?: string | null;
            /** @description 5W1H: explicit how if directly present */
            how?: string | null;
        };
        StructureResult: {
            /** @description Ordered list of structure nodes, preserving source order */
            nodes: components["schemas"]["StructureNode"][];
            node_count: number;
        };
        SelectionResult: {
            /** @description Nodes eligible for downstream processing (unchanged) */
            selected_nodes: components["schemas"]["StructureNode"][];
            /** @description Nodes excluded with explicit reasons */
            excluded_nodes: components["schemas"]["StructureNode"][];
            /** @description Per-node selection decision log (e.g. "node-0001: SELECTED", "node-0002: EXCLUDED — no structured signal detected") */
            selection_log: string[];
        };
        MeaningLens: {
            /** @enum {string} */
            lens: "modality_shift" | "scope_change" | "actor_power_shift" | "action_domain_shift" | "threshold_standard_shift" | "obligation_removal";
            detected: boolean;
            detail?: string | null;
        };
        MeaningNodeResult: {
            /** @description Links back to StructureNode.node_id */
            node_id: string;
            /** @description Original node text (not altered by Meaning) */
            source_text: string;
            lenses: components["schemas"]["MeaningLens"][];
        };
        MeaningResult: {
            /**
             * @description "executed" if AI ran, "skipped" if no API key or disabled, "error" if AI call failed
             * @enum {string}
             */
            status: "executed" | "skipped" | "error";
            /** @description Explanation when status is skipped or error */
            message?: string | null;
            /** @default [] */
            node_results: components["schemas"]["MeaningNodeResult"][];
        };
        OriginSignal: {
            /** @description Signal type (e.g. author, canonical_url, jsonld_publisher) */
            signal: string;
            value: string;
            /** @description Signal category (e.g. opengraph, twitter_card) — distribution signals only */
            category?: string | null;
        };
        OriginResult: {
            /** @enum {string} */
            status: "executed" | "skipped";
            /**
             * @description Source identity signals (author, publisher, canonical URL)
             * @default []
             */
            origin_identity_signals: components["schemas"]["OriginSignal"][];
            /**
             * @description Source metadata signals (title, publish timestamp, type)
             * @default []
             */
            origin_metadata_signals: components["schemas"]["OriginSignal"][];
            /**
             * @description Distribution metadata (OG tags, Twitter cards). Explicitly separated — does NOT override origin identity.
             * @default []
             */
            distribution_signals: components["schemas"]["OriginSignal"][];
            /**
             * @description Trace log of what was found and where
             * @default []
             */
            evidence_trace: string[];
        };
        VerificationNodeResult: {
            node_id: string;
            assertion_detected: boolean;
            /** @description Classification of the assertion if detected */
            assertion_type?: ("legal_legislative" | "court_case_law" | "government_publication" | "scientific_biomedical" | "statistical_public_data" | "corporate_financial" | "infrastructure_energy" | "historical_archival") | null;
            /** @description Whether candidate record systems exist for this assertion type */
            verification_path_available: boolean;
            /**
             * @description Candidate record systems for verification routing. Examples: Congress.gov, Federal Register, GovInfo, CourtListener, PubMed, SEC EDGAR, Census, EIA, FERC, NERC, JSTOR, National Archives
             * @default []
             */
            expected_record_systems: string[];
            verification_notes?: string | null;
        };
        VerificationResult: {
            /** @enum {string} */
            status: "executed" | "skipped";
            /** @default [] */
            node_results: components["schemas"]["VerificationNodeResult"][];
        };
        OutputResult: {
            /** @description Input-level summary (content_type, parse_status, input_size) */
            summary: {
                [key: string]: unknown;
            };
            total_nodes: number;
            selected_count: number;
            excluded_count: number;
            meaning_status: string;
            origin_status: string;
            verification_status: string;
        };
        PipelineError: {
            /** @enum {string} */
            layer: "input" | "structure" | "selection" | "meaning" | "origin" | "verification" | "output";
            error: string;
            /**
             * @description If true, downstream layers may have empty results
             * @default false
             */
            fatal: boolean;
        };
        PipelineResponse: {
            input: components["schemas"]["InputResult"];
            structure: components["schemas"]["StructureResult"];
            selection: components["schemas"]["SelectionResult"];
            meaning: components["schemas"]["MeaningResult"];
            origin: components["schemas"]["OriginResult"];
            verification: components["schemas"]["VerificationResult"];
            output: components["schemas"]["OutputResult"];
            /**
             * @description Top-level errors surfaced from any layer
             * @default []
             */
            errors: components["schemas"]["PipelineError"][];
        };
        ValidationError: {
            detail: {
                loc?: (string | number)[];
                msg?: string;
                type?: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Full pipeline result with all 7 layer outputs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResponse"];
                };
            };
            /** @description Invalid input (empty content) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid x-analyze-secret header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Content exceeds 500 KB limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
}
